feat: impove reg

diff --git a/.github/workflows/pr_validation.yml b/.github/workflows/pr_validation.yml
--- a/.github/workflows/pr_validation.yml
+++ b/.github/workflows/pr_validation.yml
@@ -1,4 +1,4 @@
-name: PR Title Validation
+name: Validate PR Title
 
 on:
   pull_request:
@@ -10,23 +10,23 @@ on:
       - unlabeled
 
 jobs:
-  validate_pr_title:
+  Validate_PR_Title:
     runs-on: ubuntu-latest
     steps:
-    - name: Check PR title
-      run: |
-        pr_title="${{ github.event.pull_request.title }}"
-        PR_TITLE_RE="^(?=.{1,90}$)(?:build|feat|ci|chore|docs|fix|perf|refactor|revert|style|test|wip)(?:\(.+\))*(?::).{4,}(?:\s\[OCH-\d+\])(?:#\d+)*(?<![\.\s])$"
-        SKIP_LABEL="autorelease: pending"
-        pr_labels="${{ toJSON(github.event.pull_request.labels) }}"
-        
-        if [[ ${pr_labels} == *"${SKIP_LABEL}"* ]]; then
-          echo "Skipping PR title validation due to the presence of the '${SKIP_LABEL}' label"
-          exit 0
-        fi
+      - name: Check PR title
+        run: |
+          SKIP_LABEL="autorelease: pending"
+          pr_labels="${{ toJSON(github.event.pull_request.labels) }}"
 
-        if [[ ! ${pr_title} =~ ${PR_TITLE_RE} ]]; then
-          echo "error: invalid PR title"
-          echo "Valid PR title is required to match pattern: ^(?=.{1,90}$)(?:build|feat|ci|chore|docs|fix|perf|refactor|revert|style|test|wip)(?:\(.+\))*(?::).{4,}(?:\s\[OCH-\d+\])(?:#\d+)*(?<![\.\s])$"
-          exit 1
-        fi
+          if [[ ${pr_labels} == *"${SKIP_LABEL}"* ]]; then
+            echo "Skipping PR title validation due to the presence of the '${SKIP_LABEL}' label"
+            exit 0
+          fi
+
+          pr_title="${{ github.event.pull_request.title }}"
+          PR_NAME_RE="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?(!)?: .+ \[O30-[0-9]+\]$"
+          if [[ ! ${pr_title} =~ ${PR_NAME_RE} ]]; then
+            echo "error: invalid PR title"
+            echo "Example: feat: subject [OCH-1234]"
+            exit 1
+          fi
