feat: impove reg

diff --git a/.github/workflows/pr_validation.yml b/.github/workflows/pr_validation.yml
--- a/.github/workflows/pr_validation.yml
+++ b/.github/workflows/pr_validation.yml
@@ -1,32 +1,29 @@
-name: PR Title Validation
+name: PR Validation
 
 on:
-  pull_request:
+  pull_request_target:
     types:
       - opened
       - synchronize
-      - edited
-      - labeled
-      - unlabeled
+      - reopened
 
 jobs:
-  validate_pr_title:
+  validate:
     runs-on: ubuntu-latest
     steps:
-    - name: Check PR title
-      run: |
-        pr_title="${{ github.event.pull_request.title }}"
-        PR_TITLE_RE="^(?=.{1,90}$)(?:build|feat|ci|chore|docs|fix|perf|refactor|revert|style|test|wip)(?:\(.+\))*(?::).{4,}(?:\s\[OCH-\d+\])(?:#\d+)*(?<![\.\s])$"
-        SKIP_LABEL="autorelease: pending"
-        pr_labels="${{ toJSON(github.event.pull_request.labels) }}"
-        
-        if [[ ${pr_labels} == *"${SKIP_LABEL}"* ]]; then
-          echo "Skipping PR title validation due to the presence of the '${SKIP_LABEL}' label"
-          exit 0
-        fi
+      - name: Validate PR title
+        run: |
+          PR_TITLE="${{ github.event.pull_request.title }}"
+          PR_URL="${{ github.event.pull_request.html_url }}"
 
-        if [[ ! ${pr_title} =~ ${PR_TITLE_RE} ]]; then
-          echo "error: invalid PR title"
-          echo "Valid PR title is required to match pattern: ^(?=.{1,90}$)(?:build|feat|ci|chore|docs|fix|perf|refactor|revert|style|test|wip)(?:\(.+\))*(?::).{4,}(?:\s\[OCH-\d+\])(?:#\d+)*(?<![\.\s])$"
-          exit 1
-        fi
+          echo "Validating PR title: '$PR_TITLE'"
+          if ! echo "$PR_TITLE" | grep -qE "^(fix|feat|refactor)(\!)?\: .+"; then
+            echo "error: invalid PR title"
+            echo "Valid PR titles must follow the Conventional Commit message format:"
+            echo "- fix: for bug fixes (SemVer patch)"
+            echo "- feat: for new features (SemVer minor)"
+            echo "- feat!: or fix!:, refactor!:, etc. for breaking changes (SemVer major)"
+            echo "Please update the PR title and try again."
+            exit 1
+          fi
+          echo "PR title validation passed!"
